/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Course {
  'id' : CourseId,
  'title' : string,
  'instructor' : Principal,
  'createdAt' : Time,
  'description' : string,
  'category' : string,
}
export type CourseId = bigint;
export interface Lesson {
  'id' : LessonId,
  'title' : string,
  'content' : string,
  'order' : bigint,
  'createdAt' : Time,
  'courseId' : CourseId,
}
export type LessonId = bigint;
export interface Question {
  'id' : QuestionId,
  'questionText' : string,
  'correctOptionIndex' : bigint,
  'options' : Array<string>,
}
export type QuestionId = bigint;
export interface Quiz {
  'id' : QuizId,
  'lessonId' : LessonId,
  'questions' : Array<Question>,
}
export interface QuizAttempt {
  'completedAt' : Time,
  'attempts' : bigint,
  'score' : bigint,
  'student' : Principal,
  'quizId' : QuizId,
}
export type QuizId = bigint;
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'attemptQuiz' : ActorMethod<[QuizId, Array<bigint>], bigint>,
  'completeLesson' : ActorMethod<[LessonId], undefined>,
  'createCourse' : ActorMethod<[string, string, string], CourseId>,
  'createLesson' : ActorMethod<[CourseId, string, string, bigint], LessonId>,
  'createQuiz' : ActorMethod<[LessonId, Array<Question>], QuizId>,
  'deleteCourse' : ActorMethod<[CourseId], undefined>,
  'deleteLesson' : ActorMethod<[LessonId], undefined>,
  'enrollInCourse' : ActorMethod<[CourseId], undefined>,
  'getAdminDashboard' : ActorMethod<
    [],
    {
      'totalEnrollments' : bigint,
      'totalUsers' : bigint,
      'totalCourses' : bigint,
    }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourse' : ActorMethod<[CourseId], Course>,
  'getCourseCompletion' : ActorMethod<[Principal, CourseId], bigint>,
  'getCourseLessonCompletions' : ActorMethod<
    [Principal, CourseId],
    Array<boolean>
  >,
  'getCourseStudents' : ActorMethod<[CourseId], Array<Principal>>,
  'getEnrolledCourses' : ActorMethod<[Principal], Array<CourseId>>,
  'getInstructorDashboard' : ActorMethod<[], Array<[CourseId, bigint]>>,
  'getLesson' : ActorMethod<[LessonId], Lesson>,
  'getQuiz' : ActorMethod<[QuizId], Quiz>,
  'getQuizAttempts' : ActorMethod<[Principal, QuizId], [] | [QuizAttempt]>,
  'getStudentDashboard' : ActorMethod<[], Array<[CourseId, bigint]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isEnrolled' : ActorMethod<[Principal, CourseId], boolean>,
  'isLessonCompleted' : ActorMethod<[Principal, LessonId], boolean>,
  'listCourseLessons' : ActorMethod<[CourseId], Array<Lesson>>,
  'listCourses' : ActorMethod<[], Array<Course>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'unenrollFromCourse' : ActorMethod<[CourseId], undefined>,
  'updateCourse' : ActorMethod<[CourseId, string, string, string], undefined>,
  'updateLesson' : ActorMethod<[LessonId, string, string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];