/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const QuizId = IDL.Nat;
export const LessonId = IDL.Nat;
export const CourseId = IDL.Nat;
export const QuestionId = IDL.Nat;
export const Question = IDL.Record({
  'id' : QuestionId,
  'questionText' : IDL.Text,
  'correctOptionIndex' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const Time = IDL.Int;
export const Course = IDL.Record({
  'id' : CourseId,
  'title' : IDL.Text,
  'instructor' : IDL.Principal,
  'createdAt' : Time,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const Lesson = IDL.Record({
  'id' : LessonId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'order' : IDL.Nat,
  'createdAt' : Time,
  'courseId' : CourseId,
});
export const Quiz = IDL.Record({
  'id' : QuizId,
  'lessonId' : LessonId,
  'questions' : IDL.Vec(Question),
});
export const QuizAttempt = IDL.Record({
  'completedAt' : Time,
  'attempts' : IDL.Nat,
  'score' : IDL.Nat,
  'student' : IDL.Principal,
  'quizId' : QuizId,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'attemptQuiz' : IDL.Func([QuizId, IDL.Vec(IDL.Nat)], [IDL.Nat], []),
  'completeLesson' : IDL.Func([LessonId], [], []),
  'createCourse' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [CourseId], []),
  'createLesson' : IDL.Func(
      [CourseId, IDL.Text, IDL.Text, IDL.Nat],
      [LessonId],
      [],
    ),
  'createQuiz' : IDL.Func([LessonId, IDL.Vec(Question)], [QuizId], []),
  'deleteCourse' : IDL.Func([CourseId], [], []),
  'deleteLesson' : IDL.Func([LessonId], [], []),
  'enrollInCourse' : IDL.Func([CourseId], [], []),
  'getAdminDashboard' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalEnrollments' : IDL.Nat,
          'totalUsers' : IDL.Nat,
          'totalCourses' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourse' : IDL.Func([CourseId], [Course], ['query']),
  'getCourseCompletion' : IDL.Func(
      [IDL.Principal, CourseId],
      [IDL.Nat],
      ['query'],
    ),
  'getCourseLessonCompletions' : IDL.Func(
      [IDL.Principal, CourseId],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  'getCourseStudents' : IDL.Func(
      [CourseId],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getEnrolledCourses' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(CourseId)],
      ['query'],
    ),
  'getInstructorDashboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(CourseId, IDL.Nat))],
      ['query'],
    ),
  'getLesson' : IDL.Func([LessonId], [Lesson], ['query']),
  'getQuiz' : IDL.Func([QuizId], [Quiz], ['query']),
  'getQuizAttempts' : IDL.Func(
      [IDL.Principal, QuizId],
      [IDL.Opt(QuizAttempt)],
      ['query'],
    ),
  'getStudentDashboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(CourseId, IDL.Nat))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isEnrolled' : IDL.Func([IDL.Principal, CourseId], [IDL.Bool], ['query']),
  'isLessonCompleted' : IDL.Func(
      [IDL.Principal, LessonId],
      [IDL.Bool],
      ['query'],
    ),
  'listCourseLessons' : IDL.Func([CourseId], [IDL.Vec(Lesson)], ['query']),
  'listCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unenrollFromCourse' : IDL.Func([CourseId], [], []),
  'updateCourse' : IDL.Func([CourseId, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateLesson' : IDL.Func([LessonId, IDL.Text, IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const QuizId = IDL.Nat;
  const LessonId = IDL.Nat;
  const CourseId = IDL.Nat;
  const QuestionId = IDL.Nat;
  const Question = IDL.Record({
    'id' : QuestionId,
    'questionText' : IDL.Text,
    'correctOptionIndex' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const Time = IDL.Int;
  const Course = IDL.Record({
    'id' : CourseId,
    'title' : IDL.Text,
    'instructor' : IDL.Principal,
    'createdAt' : Time,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const Lesson = IDL.Record({
    'id' : LessonId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'order' : IDL.Nat,
    'createdAt' : Time,
    'courseId' : CourseId,
  });
  const Quiz = IDL.Record({
    'id' : QuizId,
    'lessonId' : LessonId,
    'questions' : IDL.Vec(Question),
  });
  const QuizAttempt = IDL.Record({
    'completedAt' : Time,
    'attempts' : IDL.Nat,
    'score' : IDL.Nat,
    'student' : IDL.Principal,
    'quizId' : QuizId,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'attemptQuiz' : IDL.Func([QuizId, IDL.Vec(IDL.Nat)], [IDL.Nat], []),
    'completeLesson' : IDL.Func([LessonId], [], []),
    'createCourse' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [CourseId], []),
    'createLesson' : IDL.Func(
        [CourseId, IDL.Text, IDL.Text, IDL.Nat],
        [LessonId],
        [],
      ),
    'createQuiz' : IDL.Func([LessonId, IDL.Vec(Question)], [QuizId], []),
    'deleteCourse' : IDL.Func([CourseId], [], []),
    'deleteLesson' : IDL.Func([LessonId], [], []),
    'enrollInCourse' : IDL.Func([CourseId], [], []),
    'getAdminDashboard' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalEnrollments' : IDL.Nat,
            'totalUsers' : IDL.Nat,
            'totalCourses' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourse' : IDL.Func([CourseId], [Course], ['query']),
    'getCourseCompletion' : IDL.Func(
        [IDL.Principal, CourseId],
        [IDL.Nat],
        ['query'],
      ),
    'getCourseLessonCompletions' : IDL.Func(
        [IDL.Principal, CourseId],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    'getCourseStudents' : IDL.Func(
        [CourseId],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getEnrolledCourses' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(CourseId)],
        ['query'],
      ),
    'getInstructorDashboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(CourseId, IDL.Nat))],
        ['query'],
      ),
    'getLesson' : IDL.Func([LessonId], [Lesson], ['query']),
    'getQuiz' : IDL.Func([QuizId], [Quiz], ['query']),
    'getQuizAttempts' : IDL.Func(
        [IDL.Principal, QuizId],
        [IDL.Opt(QuizAttempt)],
        ['query'],
      ),
    'getStudentDashboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(CourseId, IDL.Nat))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isEnrolled' : IDL.Func([IDL.Principal, CourseId], [IDL.Bool], ['query']),
    'isLessonCompleted' : IDL.Func(
        [IDL.Principal, LessonId],
        [IDL.Bool],
        ['query'],
      ),
    'listCourseLessons' : IDL.Func([CourseId], [IDL.Vec(Lesson)], ['query']),
    'listCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unenrollFromCourse' : IDL.Func([CourseId], [], []),
    'updateCourse' : IDL.Func([CourseId, IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateLesson' : IDL.Func([LessonId, IDL.Text, IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };