/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Course {
    id: CourseId;
    title: string;
    instructor: Principal;
    createdAt: Time;
    description: string;
    category: string;
}
export type Time = bigint;
export interface Lesson {
    id: LessonId;
    title: string;
    content: string;
    order: bigint;
    createdAt: Time;
    courseId: CourseId;
}
export interface QuizAttempt {
    completedAt: Time;
    attempts: bigint;
    score: bigint;
    student: Principal;
    quizId: QuizId;
}
export type LessonId = bigint;
export interface Quiz {
    id: QuizId;
    lessonId: LessonId;
    questions: Array<Question>;
}
export type QuestionId = bigint;
export interface Question {
    id: QuestionId;
    questionText: string;
    correctOptionIndex: bigint;
    options: Array<string>;
}
export type CourseId = bigint;
export interface UserProfile {
    name: string;
    role: string;
}
export type QuizId = bigint;
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    attemptQuiz(quizId: QuizId, studentAnswers: Array<bigint>): Promise<bigint>;
    completeLesson(lessonId: LessonId): Promise<void>;
    createCourse(title: string, description: string, category: string): Promise<CourseId>;
    createLesson(courseId: CourseId, title: string, content: string, order: bigint): Promise<LessonId>;
    createQuiz(lessonId: LessonId, questions: Array<Question>): Promise<QuizId>;
    deleteCourse(courseId: CourseId): Promise<void>;
    deleteLesson(lessonId: LessonId): Promise<void>;
    enrollInCourse(courseId: CourseId): Promise<void>;
    getAdminDashboard(): Promise<{
        totalEnrollments: bigint;
        totalUsers: bigint;
        totalCourses: bigint;
    }>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCourse(courseId: CourseId): Promise<Course>;
    getCourseCompletion(student: Principal, courseId: CourseId): Promise<bigint>;
    getCourseLessonCompletions(student: Principal, courseId: CourseId): Promise<Array<boolean>>;
    getCourseStudents(courseId: CourseId): Promise<Array<Principal>>;
    getEnrolledCourses(student: Principal): Promise<Array<CourseId>>;
    getInstructorDashboard(): Promise<Array<[CourseId, bigint]>>;
    getLesson(lessonId: LessonId): Promise<Lesson>;
    getQuiz(quizId: QuizId): Promise<Quiz>;
    getQuizAttempts(student: Principal, quizId: QuizId): Promise<QuizAttempt | null>;
    getStudentDashboard(): Promise<Array<[CourseId, bigint]>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isEnrolled(student: Principal, courseId: CourseId): Promise<boolean>;
    isLessonCompleted(student: Principal, lessonId: LessonId): Promise<boolean>;
    listCourseLessons(courseId: CourseId): Promise<Array<Lesson>>;
    listCourses(): Promise<Array<Course>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    unenrollFromCourse(courseId: CourseId): Promise<void>;
    updateCourse(courseId: CourseId, title: string, description: string, category: string): Promise<void>;
    updateLesson(lessonId: LessonId, title: string, content: string, order: bigint): Promise<void>;
}
import type { QuizAttempt as _QuizAttempt, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async attemptQuiz(arg0: QuizId, arg1: Array<bigint>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.attemptQuiz(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.attemptQuiz(arg0, arg1);
            return result;
        }
    }
    async completeLesson(arg0: LessonId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeLesson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeLesson(arg0);
            return result;
        }
    }
    async createCourse(arg0: string, arg1: string, arg2: string): Promise<CourseId> {
        if (this.processError) {
            try {
                const result = await this.actor.createCourse(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCourse(arg0, arg1, arg2);
            return result;
        }
    }
    async createLesson(arg0: CourseId, arg1: string, arg2: string, arg3: bigint): Promise<LessonId> {
        if (this.processError) {
            try {
                const result = await this.actor.createLesson(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLesson(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createQuiz(arg0: LessonId, arg1: Array<Question>): Promise<QuizId> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuiz(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuiz(arg0, arg1);
            return result;
        }
    }
    async deleteCourse(arg0: CourseId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCourse(arg0);
            return result;
        }
    }
    async deleteLesson(arg0: LessonId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLesson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLesson(arg0);
            return result;
        }
    }
    async enrollInCourse(arg0: CourseId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.enrollInCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enrollInCourse(arg0);
            return result;
        }
    }
    async getAdminDashboard(): Promise<{
        totalEnrollments: bigint;
        totalUsers: bigint;
        totalCourses: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminDashboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminDashboard();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourse(arg0: CourseId): Promise<Course> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourse(arg0);
            return result;
        }
    }
    async getCourseCompletion(arg0: Principal, arg1: CourseId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourseCompletion(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourseCompletion(arg0, arg1);
            return result;
        }
    }
    async getCourseLessonCompletions(arg0: Principal, arg1: CourseId): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourseLessonCompletions(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourseLessonCompletions(arg0, arg1);
            return result;
        }
    }
    async getCourseStudents(arg0: CourseId): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourseStudents(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourseStudents(arg0);
            return result;
        }
    }
    async getEnrolledCourses(arg0: Principal): Promise<Array<CourseId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnrolledCourses(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnrolledCourses(arg0);
            return result;
        }
    }
    async getInstructorDashboard(): Promise<Array<[CourseId, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInstructorDashboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInstructorDashboard();
            return result;
        }
    }
    async getLesson(arg0: LessonId): Promise<Lesson> {
        if (this.processError) {
            try {
                const result = await this.actor.getLesson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLesson(arg0);
            return result;
        }
    }
    async getQuiz(arg0: QuizId): Promise<Quiz> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuiz(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuiz(arg0);
            return result;
        }
    }
    async getQuizAttempts(arg0: Principal, arg1: QuizId): Promise<QuizAttempt | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizAttempts(arg0, arg1);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizAttempts(arg0, arg1);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentDashboard(): Promise<Array<[CourseId, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentDashboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentDashboard();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isEnrolled(arg0: Principal, arg1: CourseId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isEnrolled(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isEnrolled(arg0, arg1);
            return result;
        }
    }
    async isLessonCompleted(arg0: Principal, arg1: LessonId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isLessonCompleted(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isLessonCompleted(arg0, arg1);
            return result;
        }
    }
    async listCourseLessons(arg0: CourseId): Promise<Array<Lesson>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCourseLessons(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCourseLessons(arg0);
            return result;
        }
    }
    async listCourses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCourses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCourses();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async unenrollFromCourse(arg0: CourseId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unenrollFromCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unenrollFromCourse(arg0);
            return result;
        }
    }
    async updateCourse(arg0: CourseId, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCourse(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCourse(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateLesson(arg0: LessonId, arg1: string, arg2: string, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLesson(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLesson(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QuizAttempt]): QuizAttempt | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
